name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for creating an issue. Please wait for the maintainer to review it."
        pr-message: "Hi! Thank you for contributing to AnimePedia. Please wait for a maintainer to review your Pull Request."
